//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace health_clinicClassDiagram.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("health_clinicClassDiagram.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite tip nove sale:.
        /// </summary>
        public static string birajTIPsale {
            get {
                return ResourceManager.GetString("birajTIPsale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rodjenja.
        /// </summary>
        public static string DatumRodjenja {
            get {
                return ResourceManager.GetString("DatumRodjenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novog lekara.
        /// </summary>
        public static string dodajNovogLekara {
            get {
                return ResourceManager.GetString("dodajNovogLekara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novu salu.
        /// </summary>
        public static string dodajNovuSalu {
            get {
                return ResourceManager.GetString("dodajNovuSalu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum do kada želite da vidite plan:.
        /// </summary>
        public static string drugiDatum {
            get {
                return ResourceManager.GetString("drugiDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izađi.
        /// </summary>
        public static string DugmeIzadji {
            get {
                return ResourceManager.GetString("DugmeIzadji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži.
        /// </summary>
        public static string DugmeOtkazi {
            get {
                return ResourceManager.GetString("DugmeOtkazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string DugmePotvrdi {
            get {
                return ResourceManager.GetString("DugmePotvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POČETNA STRANA.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Lekara.
        /// </summary>
        public static string IdLekar {
            get {
                return ResourceManager.GetString("IdLekar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime druge sale:.
        /// </summary>
        public static string imeDruge {
            get {
                return ResourceManager.GetString("imeDruge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime prve sale:.
        /// </summary>
        public static string imePrve {
            get {
                return ResourceManager.GetString("imePrve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum kada će se renovacija izvršiti:.
        /// </summary>
        public static string izaberiDatum {
            get {
                return ResourceManager.GetString("izaberiDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum kad se renovacija zavrsava:.
        /// </summary>
        public static string izaberiDatumKrajnji {
            get {
                return ResourceManager.GetString("izaberiDatumKrajnji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum kad renovacija pocijne:.
        /// </summary>
        public static string izaberiDatumPocetni {
            get {
                return ResourceManager.GetString("izaberiDatumPocetni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite lekara za kog želite da vidite plan:.
        /// </summary>
        public static string izaberiLekara {
            get {
                return ResourceManager.GetString("izaberiLekara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite salu:.
        /// </summary>
        public static string izaberiNazivSale {
            get {
                return ResourceManager.GetString("izaberiNazivSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite novi tip sale:.
        /// </summary>
        public static string izaberiNoviTipSale {
            get {
                return ResourceManager.GetString("izaberiNoviTipSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi opremu:.
        /// </summary>
        public static string izaberiOpremu {
            get {
                return ResourceManager.GetString("izaberiOpremu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite opremu za detaljan prikaz:.
        /// </summary>
        public static string izaberiOpremuDetaljno {
            get {
                return ResourceManager.GetString("izaberiOpremuDetaljno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite drugu salu koja će biti spojena:.
        /// </summary>
        public static string izaberisaludva {
            get {
                return ResourceManager.GetString("izaberisaludva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite prvu salu koja će biti spojena:.
        /// </summary>
        public static string izaberisalujedan {
            get {
                return ResourceManager.GetString("izaberisalujedan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite salu u koju želite da prebaciš opremu:.
        /// </summary>
        public static string izaberiSaluUKojuPrebacujes {
            get {
                return ResourceManager.GetString("izaberiSaluUKojuPrebacujes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite salu za koju menjaš tip:.
        /// </summary>
        public static string izaberiSaluZaKojuMenjasTip {
            get {
                return ResourceManager.GetString("izaberiSaluZaKojuMenjasTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite salu za koju želite da vidite opremu:.
        /// </summary>
        public static string izaberiSaluZaOpremu {
            get {
                return ResourceManager.GetString("izaberiSaluZaOpremu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite salu za podelu.
        /// </summary>
        public static string izaberiSaluZaPodelu {
            get {
                return ResourceManager.GetString("izaberiSaluZaPodelu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite salu iz koje želite da prebacite opremu:.
        /// </summary>
        public static string izaberiSaluZaPremestanjeOpreme {
            get {
                return ResourceManager.GetString("izaberiSaluZaPremestanjeOpreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iz druge u ovu.
        /// </summary>
        public static string izDrugeUOvu {
            get {
                return ResourceManager.GetString("izDrugeUOvu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iz ove u drugu.
        /// </summary>
        public static string izOveUDrugu {
            get {
                return ResourceManager.GetString("izOveUDrugu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IZVEŠTAJ.
        /// </summary>
        public static string izvestaj {
            get {
                return ResourceManager.GetString("izvestaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG.
        /// </summary>
        public static string Jmbg {
            get {
                return ResourceManager.GetString("Jmbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime:.
        /// </summary>
        public static string korisnickoIme {
            get {
                return ResourceManager.GetString("korisnickoIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krečenje.
        /// </summary>
        public static string krecenje {
            get {
                return ResourceManager.GetString("krecenje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEKAR.
        /// </summary>
        public static string lekar {
            get {
                return ResourceManager.GetString("lekar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekari:.
        /// </summary>
        public static string lekari {
            get {
                return ResourceManager.GetString("lekari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekovi:.
        /// </summary>
        public static string lekovi {
            get {
                return ResourceManager.GetString("lekovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista dostupne opreme.
        /// </summary>
        public static string listadostupneopreme {
            get {
                return ResourceManager.GetString("listadostupneopreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista dostupnih lekova.
        /// </summary>
        public static string listadostupnihlekova {
            get {
                return ResourceManager.GetString("listadostupnihlekova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAGACIN.
        /// </summary>
        public static string magacin {
            get {
                return ResourceManager.GetString("magacin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naruči lekove.
        /// </summary>
        public static string narucilekove {
            get {
                return ResourceManager.GetString("narucilekove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naruči opremu.
        /// </summary>
        public static string naruciopremu {
            get {
                return ResourceManager.GetString("naruciopremu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite informacije za novu salu:.
        /// </summary>
        public static string NovaSalaInfo {
            get {
                return ResourceManager.GetString("NovaSalaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izabrana oprema:.
        /// </summary>
        public static string odabranaOprema {
            get {
                return ResourceManager.GetString("odabranaOprema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODJAVA.
        /// </summary>
        public static string odjava {
            get {
                return ResourceManager.GetString("odjava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPCIJE.
        /// </summary>
        public static string opcije {
            get {
                return ResourceManager.GetString("opcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema:.
        /// </summary>
        public static string oprema {
            get {
                return ResourceManager.GetString("oprema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema u odabranoj sali:.
        /// </summary>
        public static string opremaUOdabranojsali {
            get {
                return ResourceManager.GetString("opremaUOdabranojsali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan za lekara.
        /// </summary>
        public static string planlekar {
            get {
                return ResourceManager.GetString("planlekar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podela Sala.
        /// </summary>
        public static string podelaSala {
            get {
                return ResourceManager.GetString("podelaSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogledaj plan.
        /// </summary>
        public static string pogledajPlan {
            get {
                return ResourceManager.GetString("pogledajPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol.
        /// </summary>
        public static string Pol {
            get {
                return ResourceManager.GetString("Pol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POMOĆ.
        /// </summary>
        public static string pomoc {
            get {
                return ResourceManager.GetString("pomoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukoliko se naručuje lek koji do sada nije naručivan, biće mu dodeljna nova šifra.
        /// </summary>
        public static string PorukaNaruciLek {
            get {
                return ResourceManager.GetString("PorukaNaruciLek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukoliko se naručuje oprema koji do sada nije naručivana, biće joj dodeljna nova šifra.
        /// </summary>
        public static string PorukaNaruciOpremu {
            get {
                return ResourceManager.GetString("PorukaNaruciOpremu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pri podeli obe ove sale zadržavaju tip originalne sale, svaka sala dobija polovinu opreme..
        /// </summary>
        public static string PorukaPodela {
            get {
                return ResourceManager.GetString("PorukaPodela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pri spajanju tip i ime nove sale će biti isti kao tip i ime prve odabrane sale..
        /// </summary>
        public static string porukaSpajanje {
            get {
                return ResourceManager.GetString("porukaSpajanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premesti opremu.
        /// </summary>
        public static string premestiOpremu {
            get {
                return ResourceManager.GetString("premestiOpremu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premeštanje opreme:.
        /// </summary>
        public static string premstanjeOpreme {
            get {
                return ResourceManager.GetString("premstanjeOpreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string Prezime {
            get {
                return ResourceManager.GetString("Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz dogadjaja po danima.
        /// </summary>
        public static string prikazdogadjaja {
            get {
                return ResourceManager.GetString("prikazdogadjaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz opreme.
        /// </summary>
        public static string prikazOpreme {
            get {
                return ResourceManager.GetString("prikazOpreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz plana:.
        /// </summary>
        public static string prikazPlana {
            get {
                return ResourceManager.GetString("prikazPlana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROMENA JEZIKA.
        /// </summary>
        public static string promenajezika {
            get {
                return ResourceManager.GetString("promenajezika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROMENA TEME.
        /// </summary>
        public static string promenateme {
            get {
                return ResourceManager.GetString("promenateme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promena namene sale.
        /// </summary>
        public static string promenaTipa {
            get {
                return ResourceManager.GetString("promenaTipa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum od kada želite da vidite plan:.
        /// </summary>
        public static string prviDatum {
            get {
                return ResourceManager.GetString("prviDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radno vreme.
        /// </summary>
        public static string RadnoVreme {
            get {
                return ResourceManager.GetString("RadnoVreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENOVIRANJE.
        /// </summary>
        public static string renoviranje {
            get {
                return ResourceManager.GetString("renoviranje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALA.
        /// </summary>
        public static string sala {
            get {
                return ResourceManager.GetString("sala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra:.
        /// </summary>
        public static string sifra {
            get {
                return ResourceManager.GetString("sifra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spajanje sala.
        /// </summary>
        public static string spajanjeSala {
            get {
                return ResourceManager.GetString("spajanjeSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalista.
        /// </summary>
        public static string Specijalista {
            get {
                return ResourceManager.GetString("Specijalista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string sr {
            get {
                return ResourceManager.GetString("sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite id za novu salu:.
        /// </summary>
        public static string unesiIdNoveSale {
            get {
                return ResourceManager.GetString("unesiIdNoveSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite količinu koju želite da naručite:.
        /// </summary>
        public static string unesiKolicinu {
            get {
                return ResourceManager.GetString("unesiKolicinu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite lek koji želiš da naručiš:.
        /// </summary>
        public static string unesiLekNarucivanje {
            get {
                return ResourceManager.GetString("unesiLekNarucivanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesi opremu koju želiš da naručiš.
        /// </summary>
        public static string unesiOpremuNarucivanje {
            get {
                return ResourceManager.GetString("unesiOpremuNarucivanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPRAVNIK.
        /// </summary>
        public static string Upravnik {
            get {
                return ResourceManager.GetString("Upravnik", resourceCulture);
            }
        }
    }
}
